# Generated by Django 3.2.4 on 2022-02-11 13:59

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionimage',
            options={'verbose_name': 'Sampled image', 'verbose_name_plural': 'Sampled images'},
        ),
        migrations.RenameField(
            model_name='descriptionimage',
            old_name='dimentions',
            new_name='dimension',
        ),
        migrations.AlterField(
            model_name='descriptionimage',
            name='file',
            field=models.ImageField(blank=True, help_text='Image file', null=True, upload_to=photo.models.change_path_upload, verbose_name='Image file'),
        ),
    ]
