version: "3.3"
services:
  ###############
  #Load Balancer#
  postgres-kong-database:
    image: postgres:11
    ports:
      - "9955:5432"
    environment:
      - POSTGRES_PASSWORD=kong
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  #
  load-balancer:
    image: andrebaceti/autoboostrap-kong:1.0
    depends_on:
      - postgres-kong-database
    ports:
      - "8080:8000"
      - "8001:8001"
      - "8443:8443"
      - "7946:7946"
      - "7946:7946/udp"
  ###############

  ##########
  #RabbitMQ#
  rabbitmq-main:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=pumpwood
      - RABBITMQ_DEFAULT_PASS=pumpwood
  #########

  #####################
  # Auth Microservice #
  test-db-pumpwood-auth:
    image: southamerica-east1-docker.pkg.dev/serene-boulder-340918/private-images/test-db-ai-photo-sampler:$TEST_DB_PUMPWOOD_AUTH
    ports:
      - 7000:5432
    shm_size: 512mb
    restart: always
    environment:
      - KONG_API=http://load-balancer:8001/
      - SERVICE_URL=http://test-db-pumpwood-auth:5000/

  pumpwood-auth-app:
    image: southamerica-east1-docker.pkg.dev/serene-boulder-340918/private-images/ai-photo-sampler-app:$PUMPWOOD_AUTH_APP

  pumpwood-auth-admin-static:
    image: southamerica-east1-docker.pkg.dev/serene-boulder-340918/private-images/ai-photo-sampler-static:$PUMPWOOD_AUTH_STATIC
