# Generated by Django 3.2.4 on 2022-02-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.models
import pumpwood_communication.serializers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, help_text='Unique hash associated with each photo from app', max_length=40, null=True, unique=True, verbose_name='Unique hash')),
                ('app_label', models.CharField(blank=True, help_text='Label used on app', max_length=154, null=True, verbose_name='App label')),
                ('description', models.CharField(blank=True, help_text='Short description', max_length=154, null=True, verbose_name='Short description')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about the photo', verbose_name='Notes')),
                ('dimentions', models.JSONField(blank=True, default=dict, encoder=pumpwood_communication.serializers.PumpWoodJSONEncoder, help_text='Key/Value Dimentions', verbose_name='Dimentions')),
                ('extra_info', models.JSONField(blank=True, default=dict, encoder=pumpwood_communication.serializers.PumpWoodJSONEncoder, help_text='Extra information', verbose_name='Extra information')),
                ('file', models.ImageField(blank=True, help_text='Extra information', null=True, upload_to=photo.models.change_path_upload, verbose_name='Extra information')),
                ('image_created_at', models.DateTimeField(help_text='Date/Time image creation', null=True, verbose_name='Date/Time image creation')),
                ('image_uploaded_at', models.DateTimeField(help_text='Date/Time image uploaded', null=True, verbose_name='Date/Time image uploaded')),
                ('obj_created_at', models.DateTimeField(null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('image_created_by', models.ForeignKey(help_text='User that created image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='User that created image')),
                ('obj_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_uploaded', to='experiment.descriptionexperimentteam')),
            ],
            options={
                'db_table': 'photo__description',
                'unique_together': {('description', 'team')},
            },
        ),
    ]
