# Generated by Django 3.2.4 on 2022-04-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_rename_dimension_descriptionimage_dimentions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionimage',
            old_name='dimentions',
            new_name='dimensions',
        ),
    ]
